pipeline {
    agent any
    
    parameters {
        choice (choices: ["dev", "qa"], description: "Wich environment to test", name: "environment" )
        string(defaultValue: "regression", description: "Test tags to execute", name: "tag" )
    }
    
    environment{
        def imageName = "python-api-testing"
        def containerName = "python-api-testing-${env.BUILD_NUMBER}"
    }
    
    stages {
        
        stage("Clean Up"){
            steps {
                deleteDir()
            }
        }
        
        stage("Clone Repository"){
            steps {
                sh "git clone https://github.com/gorilla-leo/pytest-learning-lab.git"
            }
        }

        stage("Build Image"){
            steps {
                dir('pytest-learning-lab/API-Testing'){
                    sh "docker build -t ${imageName} ."
                }
            }
        }
        
        stage("Execute Tests"){
            steps {
                dir('pytest-learning-lab/API-Testing'){
                    sh "docker run -d --env ENV=${params.environment} --name ${containerName} ${imageName}"
                    
                    script{
                        if(params.tag == "regression"){
                            sh "docker exec -i ${containerName}  pytest --html=./report/report.html --self-contained-html"
                        }else{
                            sh "docker exec -i ${containerName}  pytest --html=./report/report.html --self-contained-html -m ${params.tag}"
                        }
                    }
                }
            }
        }
     }
    post {
        always {
            dir('pytest-learning-lab/API-Testing'){
                sh "rm -rf report; mkdir report"
                sh "docker cp ${containerName}:/python-api-testing/report/report.html ./report"
            }
            echo "Cleanup"
            sh "docker stop ${containerName}"
            sh "docker rm ${containerName}"
            //docker rmi $IMAGE_NAME
          // publish html
          publishHTML target: [
              allowMissing: false,
              alwaysLinkToLastBuild: false,
              keepAll: true,
              reportDir: 'pytest-learning-lab/API-Testing/report',
              reportFiles: 'report.html',
              reportName: 'API Testing Report'
            ]        
        }
    }
}