pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps {
                echo "Clean......"
            }
        }
        
        stage("Clone Repo"){
            steps {
                echo "Clone......"
            }
        }

        stage("Build"){
            steps {
                echo "Build......"
            }
        }
        stage("Test"){
            steps {
                echo "Test......"
            }
        }

     }
}
